# Network architecture
embed_hidden: 128
enc_stacks: 3
ff_hidden: 512
enc_heads: 16
query_hidden: 360
att_hidden: 256
crit_hidden: 256
n_history: 3
p_dropout: 0.1

# Logging
proj_name: "encode_attend_navigate"
log_interval: 200

# Training
steps: 20000
batch_size: 256
max_len: 50
dimension: 2
model_path: "model.pt"
test: True
test_steps: 10
device: "cuda:0"

# Optimizer
lr: 0.001
lr_decay_rate: 0.96
lr_decay_steps: 5000